export const config = {
  serverPort: 5555,
  maxNameLength: 16,
  roundLength: 60,
  betweenLength: 5,
  maxScorePerGuess: 1000,
  words: [
    "Apple",
    "Banana",
    "Elephant",
    "Guitar",
    "Rainbow",
    "Mountain",
    "Sunflower",
    "Pizza",
    "Robot",
    "Clock",
    "Car",
    "Ocean",
    "Book",
    "Key",
    "Chair",
    "Dragon",
    "Tree",
    "Hat",
    "Train",
    "Fish",
    "Star",
    "Cupcake",
    "Bridge",
    "Dolphin",
    "Moon",
    "Beach",
    "Firetruck",
    "Penguin",
    "Telescope",
    "Camera",
    "Ship",
    "Umbrella",
    "Snowman",
    "Butterfly",
    "Wizard",
    "Piano",
    "Jungle",
    "Lighthouse",
    "Turtle",
    "Horse",
    "Ice Cream",
    "Kite",
    "Map",
    "Castle",
    "Rocket",
    "Lion",
    "Cactus",
    "Basketball",
    "Flower",
    "Spider",
    "Helicopter",
    "Tiger",
    "Soccer",
    "Magnet",
    "Moonwalk",
    "Parachute",
    "Pirate",
    "Rain",
    "Sailboat",
    "Sword",
    "Telephone",
    "Vampire",
    "Waterfall",
    "Whale",
    "Zoo",
    "Alarm Clock",
    "Backpack",
    "Bubble Bath",
    "Campfire",
    "Chopsticks",
    "Dinosaur",
    "Ferris Wheel",
    "Garden",
    "Hot Air Balloon",
    "Jigsaw Puzzle",
    "Muffin",
    "Painting",
    "Roller Coaster",
    "Space Invader",
    "Teddy Bear",
    "Windmill",
    "Yo yo",
    "Zeppelin",
    "Fireworks",
    "Hiking",
    "Jellyfish",
    "Origami",
    "Popcorn",
    "Sandbox",
    "Skyscraper",
    "Wristwatch",
  ],
};
